### ISSUE TITLE
Is it possible to enable it by default?

### ISSUE THREAD

**Issue by rbasso** [MichaelXavier/tasty-fail-fast#2]
Hi,

I'm new to _tasty_, so this is probably a dumb question.

I'm considering using `tasty-fail-fast` in the test suites for the Haskell exercises in http://exercism.io , but because the tests are supposed to be run by the students, we cannot expect them to always type `stack test --test-arguments --fail-fast`. Maybe I'm missing something, but I couldn't find a clean solution to this.

Is there any simple way to enable _fail-fast_ in the source code, so that we don't have to supply `--fail-fast` in the command line?

**Comment by MichaelXavier** [comment]
Hi,

So it looks like I [defaulted fail fast to off](https://github.com/MichaelXavier/tasty-fail-fast/blob/master/src/Test/Tasty/Ingredients/FailFast.hs#L48). I think this is the reasonable thing to do.

You can however on the haskell side inject the fail fast option and set it to true. It looks like `localOption :: IsOption v => v -> TestTree -> TestTree` is what you want. So if you want this applied at the root, your main would look something like `defaultMain $ localOption (FailFast True) $ [ .... ]`. I noticed that there's no actual example code in this repo so I'll go ahead and set that up and post here when done. Seems worthy of a release too.

**Comment by MichaelXavier** [comment]
Oh, actually I realized the home page on the package includes an example:

``` haskell
defaultMainWithIngredients (map failFast defaultIngredients) tests
```

So for your case I think you want:

```
defaultMainWithIngredients (map failFast defaultIngredients) (localOption (FailFast True) tests)
```

**Comment by rbasso** [comment]
Thank you for you help! :smile: 

Unfortunately, that doesn't seems to work:

``` haskell
import Test.Tasty
import Test.Tasty.HUnit
import Test.Tasty.Ingredients.FailFast

main :: IO ()
main = defaultMainWithIngredients (map failFast defaultIngredients) (localOption (FailFast True) tests)
  where
    tests = testGroup "Failure && Success" $
              [ testCase "Failure" $ True @?= False
              , testCase "Success" $ True @?= True ]
```

```
$ stack runghc Tests.hs

Failure && Success
  Failure: FAIL
    expected: False
     but got: True
  Success: OK

1 out of 2 tests failed (0.00s)
```

```
$ stack runghc Tests.hs -- --fast-fail

Failure && Success
  Failure: FAIL
    expected: False
     but got: True
  Success: 

2 out of 2 tests failed (0.00s)
```

Maybe this can't be set that way: 

> Adjusting and querying options
> Normally options are specified on the command line. But you can
> also have different options for different subtrees in the same tree,
> using the functions below.
> 
> Note that /ingredient options/ (number of threads, hide successes
> etc.) set in this way will not have any effect. This is for modifying
> per-test options, such as timeout, number of generated tests etc.
> ...
> localOption :: IsOption v => v -> TestTree -> TestTree
> Locally set the option value for the given test subtree
> ...

**Comment by MichaelXavier** [comment]
I think you may need to ask @feuerbach about this. I think it may be impossible. Looks like internally OptionSet is a Map and `lookupOption` which my library must use to get the selection does a lookup with defaulting. I would just reimplement `lookupOption` to have different defaulting behavior but the constructor for OptionSet isn't exported so its impossible.

**Comment by rbasso** [comment]
Thank you very much for your time, @MichaelXavier. I appreciate the explanation. :smile:

**Comment by UnkindPartition** [comment]
You could do this by setting the environment variable -- either externally in the environment where you run the tests, or directly in `main` before you call `defaultMain` (using `setEnv`).

**Comment by rbasso** [comment]
Interesting solution! Thanks, @feuerbach .

But now I have already rewritten most of the exercises to use `hspec`, so we'll probably stick with it for a while. It was the simplest solution I could find at the time:

``` haskell
import Test.Hspec.Runner (configFastFail, defaultConfig, hspecWith)

main :: IO ()
main = hspecWith defaultConfig {configFastFail = True} specs
```
