### ISSUE TITLE
Test suite hangs at the end after fast fail

### ISSUE THREAD

**Issue by thomasjm** [MichaelXavier/tasty-fail-fast#5]
This is a little mysterious and I haven't tracked it down all the way, but I was hoping to get some help understanding it...

I have a test suite which uses `tasty`, `tasty-hspec`, and `hspec-webdriver` to run Selenium tests. When I tried to use `tasty-fail-fast`, it fails fast as expected (all the tests print out in the console with blank descriptions) but then the test process hangs, and you have to Ctrl+C it to exit it.

I set up an instrumented version of `tasty` with print statements in the `launchTestTree` function, and I observe that things are getting hung up on the `waitForResources` line. There seems to be a single resource that stays in the `Created` state forever.

I'm not familiar with Tasty's internals, I'm forced to conclude that the method by which `tasty-fail-fast` wraps an `Ingredient` (where it does an STM operation to modify the `StatusMap` and fill in `Done` for all the statuses) is not totally safe.

Do you have any thoughts? Any feedback from @feuerbach would be appreciated also. Thanks!

**Comment by UnkindPartition** [comment]
Can you try to reduce your test suite? Try removing selenium, hspec-webdriver, tasty-hspec, and see at what point the bug no longer reprduces.

**Comment by thomasjm** [comment]
Okay, I've isolated it to (my fork of) `hspec-webdriver`.

I have my own version of `hspec-webdriver` that does a few things differently. One of these things is that it uses `Test.Hspec._afterAll` to close the Selenium sessions when everything is done. If I remove the `_afterAll`, the hanging bug goes away.

I know that `_afterAll` internally modifies the Hspec spec, replacing a `Node` with a `NodeWithCleanup` where the `NodeWithCleanup` contains an extra action to be executed after the test. So it seems like something weird is happening with the cleanup action.

I see that something is going on with Tasty resources inside `tasty-hspec` in the `NodeWithCleanup` case:

```
specTreeToTestTree :: H.SpecTree () -> T.TestTree
specTreeToTestTree spec_tree =
  case spec_tree of
    H.Node name spec_trees -> ...
    H.NodeWithCleanup cleanup spec_trees ->
      T.WithResource (T.ResourceSpec (return ()) cleanup) (const test_tree)
     where
      test_tree :: T.TestTree
      test_tree = specTreeToTestTree (H.Node "(unnamed)" spec_trees)
    H.Leaf item -> ...
```

Is it possible this resource is never getting cleaned up when we fail fast?

**Comment by thomasjm** [comment]
Oh, and it only happens with `--num-threads 1`. 

I managed to put together a simple repro: https://github.com/thomasjm/tasty-fail-fast-example

**Comment by UnkindPartition** [comment]
I think this may be the same bug as https://github.com/feuerbach/tasty/issues/75. Tasty is not aware of the early exit and so is not ready to release the resources, and yet it waits until all of them have been released.

**Comment by UnkindPartition** [comment]
@thomasjm could you try the current tasty master and see if it fixes the problem?

**Comment by thomasjm** [comment]
Yep it works on my repro example :+1: 

Ctrl+C seems to work too now.

**Comment by MichaelXavier** [comment]
Nice, glad you guys worked it out! Would it make sense for this library to set a lower bound or anything?

**Comment by thomasjm** [comment]
Not sure, I would love to see the latest versions on Stackage (it seems Tasty 1.x isn't even on recent nightlies)

**Comment by UnkindPartition** [comment]
@MichaelXavier depends on your philosophy as a maintainer. I wouldn't bother if I were you — people should expect bugs when they are not using the latest package versions. Also note that if you do decide put those lower bounds, you'll have to put them for all released versions, otherwise the solver might just pick the old versions for both tasty and tasty-fail-fast.

@thomasjm ugh that's bad. I left a comment at https://github.com/fpco/stackage/issues/3178#issuecomment-371448088. But you know you can mix hackage and stackage packages right?

**Comment by thomasjm** [comment]
Yep I'm aware, I just try to avoid it :). Looks like this issue is done so I'll hit close, thanks for the fix!
